- name: Javascript
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        creates: ~/.nvm/nvm.sh

    - name: Install VS Code extensions for JS
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - dbaeumer.vscode-eslint
        - svipas.prettier-plus
        - christian-kohler.npm-intellisense
        - pmneo.tsimporter
        - sburg.vscode-javascript-booster
