- name: Main OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install playbook dependencies
      become: yes
      package: name={{ item }} state=latest
      with_items:
        - curl
        - git

- import_playbook: python/main.yml
- import_playbook: javascript/main.yml

- import_playbook: vscode/main.yml
- import_playbook: vscode/customise.yml
- import_playbook: python/vscode.yml
- import_playbook: javascript/vscode.yml
