- name: OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install playbook dependencies
      become: yes
      package:
        state: present
        name: [
          'curl',
          'git'
        ]

- import_playbook: vscode/main.yml
- import_playbook: python/main.yml
- import_playbook: javascript.yml
