- name: Python
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        creates: ~/.nvm/nvm.sh
