- name: Customise VS Code
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - dbaeumer.vscode-eslint
        - svipas.prettier-plus
        - christian-kohler.npm-intellisense
        - pmneo.tsimporter
        - sburg.vscode-javascript-booster
