- name: VS Code
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_tasks: "{{ ansible_os_family | lower }}.yml"

    - name: Install VS Code
      become: yes
      package:
        name: code
        state: present

    - name: Install general VS Code extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - akamud.vscode-theme-onedark
        - emmanuelbeziat.vscode-great-icons
        - vscodevim.vim
        - visualstudioexptteam.vscodeintellicode
        - editorconfig.editorconfig
        - mechatroner.rainbow-csv
        - tamasfe.even-better-toml
