- name: Python
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_tasks: "{{ ansible_os_family | lower }}.yml"

    - name: Install pyenv
      shell: >
        curl -sSL https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
      args:
        creates: ~/.pyenv

    - name: Install Poetry
      shell: >
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      args:
        creates: ~/.poetry/bin/poetry

    - name: Install VS Code extensions for Python
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ms-python.python
        - magicstack.magicpython
        - batisteo.vscode-django
        - shamanu4.django-intellisense
