- name: Customise VS Code
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ms-python.python
        - magicstack.magicpython
        - batisteo.vscode-django
        - shamanu4.django-intellisense
